# Yarn v4 configuration: https://yarnpkg.com/configuration/yarnrc.

nodeLinker: node-modules

# Share a global cache between workspaces.
enableGlobalCache: true

# Opt out of telemetry.
enableTelemetry: false

# Enable immutable mode for extra security in CI.
enableImmutableCache: '${CI-false}'
enableImmutableInstalls: '${CI-false}'

# Enable hardened mode for extra security in CI, at the cost of slower installs.
enableHardenedMode: '${CI-false}'
