name: Shared GitHub action setup
description: Sets up Node.js with Yarn v4 and optionally installs Firebase CLI and project dependencies
inputs:
  install-deps:
    required: false
    default: 'false'
  install-firebase:
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Enable corepack
      shell: bash
      run: corepack enable
    - name: Activate Yarn v4
      shell: bash
      run: corepack prepare yarn@4 --activate
    - name: Install Firebase CLI
      if: inputs.install-firebase == 'true'
      shell: bash
      run: npm install -g firebase-tools
    - name: Install Dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: yarn install
