name: Preview staging PWA on PR
on:
  pull_request:
    paths:
      - 'packages/pwa/**'
      - 'packages/shared/**'
      - 'packages/sharedClient/**'
      - '.firebaserc'
      - '.prettierrc'
      - 'eslint.config.mjs'
      - 'firebase.json'
      - 'package.json'
      - 'tsconfig.json'
      - 'yarn.lock'
      - '.github/actions/setup-workflow/**'
      - '.github/workflows/firebase-hosting-pull-request.yml'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  preview_hosting_stag:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: CI setup action for Firebase deploy
        uses: ./.github/actions/setup-workflow
        with:
          install-deps: 'true'
          install-firebase: 'true'
      - name: Validate PWA
        run: yarn run validate:pwa
      - name: Build PWA
        run: yarn run build:pwa
      - name: Deploy PWA
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_drivechart_STAG }}
          projectId: drivechart-stag
